from pathlib import Path
from fractions import Fraction as Q
import json,hashlib,subprocess,shutil,platform
W=Path(__file__).parent;C=Path('/root/WU088_HH_ENERGY06C_20261009');P=W/'repo/research/r31ao_unequal_ladder/ncp_energy06e_certificate_20261010_v1';R=W/'run'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def put(n,x):(R/n).write_text(json.dumps(x,indent=2,ensure_ascii=False)+'\n')
def loc(p,l):return {'path':str(p),'line':l,'sha256':sha(p)}
abi={'schema':'PAIRED_STAGE_RECEIPT_ABI_V1','gas':4,'photons':[128,33],'guard_N':128,'guard_U':128,'enclosures':'native f64 pairs preserved','compensation':['ledger5','energy1','HH2'],'ledger':'native checkpoint entire bytes','theta':'fixed0 only; family OPEN','lambda':'OFF0/LCS1 only','half2':'requires exact accepted half1 native checkpoint; weights-only rejected','source_binding':sha(P/'FINAL_SOURCE_BINDING_V4.json')}
put('RECEIPT_ABI.json',abi);abih=sha(R/'RECEIPT_ABI.json');shutil.copyfile(R/'RECEIPT_ABI.json',P/'RECEIPT_ABI.json')
f=P/'src/paired_stage_receipt.rs';s=f.read_text().replace('id.abi_sha256.len()==64 && id.abi_sha256.bytes().all(|x|x.is_ascii_hexdigit()&&!x.is_ascii_uppercase())','id.abi_sha256=="'+abih+'"').replace('abi_sha256:"a".repeat(64)','abi_sha256:"'+abih+'".into()');f.write_text(s)
# Independent simple rational proof, quantified n>=256 through sign and ordering.
proof=[]
for k in [1,3,5,7]:
 for r in [0,1,2]:
  a=Q(r)-Q(k,2);b=Q(r)+Q(3,2);assert 256+a>0 and b>a and b>0
  proof.append({'k':k,'r':r,'a':str(a),'b':str(b),'n_ge_256_positive':True,'b_minus_a':str(b-a)})
q=Q(64,257);factor=1/(1-q);assert factor==Q(257,193)<Q(26471,19815)
put('C1_RATIONAL_TAIL.json',{'proof':'for all n>=256: 0<n+a<n+b, so ratio<64/(n+1)<=64/257; sum tail from T256','families':proof,'q':str(q),'factor':str(factor),'original_factor_unchanged':'26471/19815','whole_integrand_certified':False})
owner=W/'original_owner_dependency/src';cb=W/'c1/source/gap_closure_20261001_g0_g6_v1/validated_callback/callback.cpp';lm=W/'c1/source/wide_domain_20261001_v1/log_native_driver/log_map.hpp';worker=W/'c1/source/wide_domain_20261001_v1/log_native_driver/primitive_worker.cpp'
put('CERTIFICATE_PRECONDITIONER_AUDIT.json',{'status':'SOURCE_CHAIN_INSPECTED__NATIVE_AND_FAMILY_CERTIFICATES_OPEN','source_binding_sha256':sha(P/'FINAL_SOURCE_BINDING_V4.json'),'ABI_sha256':abih,'reduced_source':loc(owner/'coupled_primary.rs',465),'HH_source':loc(owner/'hh_primary_extension.rs',66),'preconditioner':loc(owner/'hh_primary_extension.rs',514),'definition':'M=I-dt F_y with full derivative of P=N/(1+dt opacity(y)); C=inverse4(I-dt midpoint(F_y at certified centre)); original candidate supplied C not promoted','free_choice_C_allowed':False,'certificate_producer_implemented':False,'source_authority_hashes':{p.name:sha(p)for p in owner.glob('*.rs')},'support':{'lambda_fixed_theta':'B_lambda=T_lambda=0; prior gas and photon derivatives retained','free_electron_temperature':'FT03 interval AD all four gas coordinates; source domains required','cutoffs':'fixed AtomicProvider cross-section at exact 33 energy nodes; arbitrary threshold/energy derivatives OPEN','spectral_hat':'fixed geometry remap interval hat and signed tangent; family knot crossings need branch enclosure','energy_angle_geometry':'128x33 fixed native grid only; theta family OPEN','lower_guard':'lambda tangent N/U carry supported in existing compile-only remap','upper_guard':'unsupported, explicit refusal above20eV','HH_temperature':'entire gas box T in [35000,60000] K; neutral boundary no division'}})
put('TANGENT_CHAIN.json',{'status':'EXACT_ALGEBRA_AND_SOURCE_INSPECTION_ONLY','equations':['N_i=T_i Pprev+B_i','P_i=N_i/(1+dt_i opacity(y_i))','P_i_prime=N_i_prime/den-N_i*dt_i*opacity_prime/den^2','M_i v_i=vprev+dt_i(F_N T_i Pprev_prime+c_H q_i)','c_H=(1,0,0,-13.6) for original CHI[0] (inspect frozen value)'],'dB_dlambda':'0 at fixed theta','dPprev_dlambda':'generally nonzero','dN_dlambda':'generally nonzero','actual_derivative_enclosure':None,'family_certificate':None,'no_second_half_reset':True})
# Separate objects are deliberately OPEN; no arbitrary input claim authenticates source derivatives.
for n,kind in [('ACTUAL_COUPLED_ROOT_CERTIFICATE.json','fixed point actual native producer'),('UNIFORM_PARAMETER_FAMILY_CERTIFICATE.json','uniform theta/lambda family')]:
 put(n,{'kind':kind,'status':'OPEN','certificate':None,'source_binding_sha256':sha(P/'FINAL_SOURCE_BINDING_V4.json'),'ABI_sha256':abih,'input_sha256':sha(P/'inputs/HH_ENERGY06D_20261010_v1/inputs/OWNER_PREBE_FINAL_BINARY.jsonl'),'preconditioner_sha256':None,'strict_image_inclusion':None,'scaled_contraction':None,'derivative_enclosure':None,'root_certified':False})
D=P/'inputs/HH_ENERGY06D_20261010_v1';put('BIRTH_SCHEME_LEDGER.json',{'status':'ORIGINAL_SAVED_MEASURES_ONLY','source_law':json.loads((D/'inputs/SOURCE_LAW_AND_SCHEMES.json').read_text()),'angular_birth_sha256':sha(D/'results/science/ANGULAR_BIRTH.json'),'spacetime_addendum_sha256':sha(P/'inputs/HH_ENERGY06D_SPACETIME_ADDENDUM_20261010.json'),'space_time_TV_over_W':'1/2','half2_weights_only':True,'accepted_half1_receipt':None,'accepted_events':'native compensated half1+half2 only; diagnostic full excluded','actual_paired_defect':None,'local_gate':'strict<2e-4 source difference()','public_gate':'strict<2e-3 source width()','ledger_gate':'<=1e-12 original per-stage native residuals'})
missing=[('WHOLE_COMPLEX_POSITIVE_MARGIN',loc(cb,110),'No quantified whole log/physical trial-box enclosure for Re(t),Re(u),Re(a+t),Re(b+u),Re(sigma)>original exact margin'),('HOLOMORPHIC_COMPOSITION_AND_SIGMA_INVERSE',loc(cb,83),'Whole-box margin, nonzero denominators, principal-power/log branches and parameter-integral holomorphy not closed'),('MAPPED_Z_AND_BRANCH',loc(cb,89),'z=-s/(2 sigma) whole complex L1<=64 or original evaluator admissibility not proved for every trial box'),('SIGNED_ORDERED107_IDENTITY_RANK',loc(cb,199),'Whole-field exact107 coefficient/sign/order and radial0..2 identities not a completed theorem'),('ORDER1_ANALYTIC_ENCLOSURE',loc(lm,56),'joint_holomorphy_proved=false remains fail closed; order1 is analytic enclosure not radial derivative')]
put('C1_FULL_BOX_PREMISE.json',{'status':'MISSING_PREMISE','source_feasibility':loc(C/'c1/FULL_BOX_FEASIBILITY.json',1),'scope_proposal':loc(C/'run/TWO_CELL_NEW_SCOPE_PROPOSAL_V3.json',1),'scalar_conditional_tail':'64/257,257/193 independently exact verified','original_factor':'26471/19815 unchanged','missing':[{'code':'MISSING_PREMISE','premise':k,'location':l,'detail':d}for k,l,d in missing],'coverage':{'bounded':24,'total':289,'unbounded':265,'epsilon_C':None,'epsilon_R':None,'B22':'OPEN_UNDETERMINED'},'whole_integrand_analytic':False,'native_integrations':0})
live=json.loads((R/'LIVE_IDENTITY.stdout').read_text());live['scope_proposal_sha256']=sha(C/'run/TWO_CELL_NEW_SCOPE_PROPOSAL_V3.json');put('C1_LIVE_BINDING_PROPOSAL.json',{'status':'NEW_IDENTITY_ONLY_PROCESS_OBSERVED__FUTURE_SCIENCE_BINDING_OPEN','observation':live,'C1_candidate_ABI':'15 positional bounded integration args retained; main refuses science; --identity-live preparation only','source_ABI_hash':sha(worker),'compiler_and_flags':json.loads((R/'C1_BUILD.json').read_text()),'plan_source_scope_proposal_sha256':sha(C/'run/TWO_CELL_NEW_SCOPE_PROPOSAL_V3.json'),'precision':128,'radius_exp':-57,'future_execution_binding':None,'authorization':None,'UID_policy':'observed UID0 caps0; policy admission OPEN','reserve_admission':False,'request_ready':False,'dispatch_count':0,'retry':0})
put('BLOCKERS.json',{'status':'OPEN','blockers':['accepted native half1 producer return absent; half2 remains weights-only','actual source-bound coupled root, preconditioner provenance and derivative enclosure absent','uniform theta/lambda family evaluator and certification absent','C1 whole-box quantified premises missing','fresh authorized scientific worker live binding, UID/reserve and exact new human authorization missing'],'not_requested':'no new scientific authorization requested by this return'})
put('CLAIM_LEDGER.json',{'source_bytes':'checked','receipt':'candidate compiled/synthetic contracts only; no actual accepted receipt','root':'OPEN','family':'OPEN','C1':'scalar conditional tail only; full-box OPEN','HH_OFF':'S0 control','ON06G':{'macros':256,'time_s':3.2e11,'rerun':False},'coverage':'24/289;265 unbounded','epsilon_C':None,'epsilon_R':None,'B22':'OPEN','physical':'HOLD','production':'HOLD','owner_claims':'REI/HE/CR separate, no HH pass transfer','new_science_dispatch':0,'candidate_promoted':False})
# Preserve all original failures, authority and proof inventory, not new synthetic scientific arrays.
shutil.copyfile(C/'run/ROOT_AND_GATE_RESULTS.json',R/'ORIGINAL_ROOT_AND_GATE_RESULTS.json');shutil.copyfile(C/'run/TWO_CELL_NEW_SCOPE_PROPOSAL_V3.json',R/'TWO_CELL_NEW_SCOPE_PROPOSAL_V3.json');shutil.copyfile(C/'c1/FULL_BOX_FEASIBILITY.json',R/'FULL_BOX_FEASIBILITY.json')
(R/'RUN_LEDGER.jsonl').write_text(json.dumps({'event':'SOURCE_READ_AND_BOUND','historical_preservation_files':len(json.loads((R/'INVENTORY_BEFORE.json').read_text())['files']),'scientific_dispatch':0})+'\n'+json.dumps({'event':'CONTRACT_AND_LIVE_IDENTITY','new_native_science':0,'live_pid':live['pid'],'process_exited':True,'future_binding':None})+'\n')
