from pathlib import Path
import hashlib,json,sys,subprocess,os,shutil
W=Path(__file__).parent;P=W/'repo/research/r31ao_unequal_ladder/ncp_phys01_mixed_contract_20261010_v1';R=W/'run';D=W/'inputs/HH_PHYS01_20261010_v1';E=Path('/root/WU088_HH_ENERGY06E_20261010')
sys.path.insert(0,str(P/'src'));from mixed_family import *
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def serial(x):
 if isinstance(x,Box):return {'lo':str(x.lo),'hi':str(x.hi)}
 if isinstance(x,Q):return str(x)
 if isinstance(x,Jet):return {'value':serial(x.value),'gradient':[serial(i)for i in x.gradient],'hessian':[[serial(i)for i in row]for row in x.hessian]}
 if isinstance(x,ToyState):return {'x':serial(x.x),'photons':serial(x.photons)}
 if isinstance(x,dict):return {k:serial(v)for k,v in x.items()}
 if isinstance(x,(list,tuple)):return [serial(i)for i in x]
 return x
def put(n,x):(R/n).write_text(json.dumps(serial(x),indent=2,ensure_ascii=False)+'\n')
# New import gate only; HH-PHYS01 old scientific suite is deliberately not run.
cmd=['python3',str(D/'verify_delivery.py')];env=dict(os.environ,PYTHONDONTWRITEBYTECODE='1');r=subprocess.run(cmd,capture_output=True,env=env);(R/'IMPORT_MANIFEST.stdout').write_bytes(r.stdout);(R/'IMPORT_MANIFEST.stderr').write_bytes(r.stderr);assert r.returncode==0
cmd2=['python3','-W','error','-m','unittest','discover','-s',str(P/'tests'),'-v'];r2=subprocess.run(cmd2,capture_output=True,env=env);(R/'NEW_TESTS_FINAL.stdout').write_bytes(r2.stdout);(R/'NEW_TESTS_FINAL.stderr').write_bytes(r2.stderr);assert r2.returncode==0
initial=ToyState(Jet.constant(Q(1,4)),Jet.constant(Q(1,10)));synth={k:synthetic_family(initial,Box(Q(0),Q(1)),Box(Q(0),Q(1,5)),Q(1,16),k)for k in ['full','twohalf']}
put('MIXED_RESPONSE.json',{'status':'SYNTHETIC_DISCRETE_FAMILY_ENCLOSURE_ONLY__ACTUAL_OWNER_OPEN','observables':{'D':'x(lambda,S)-x(0,S)','I':'x(lambda,S)-x(lambda,0)-x(0,S)+x(0,0)','HH_defect':'D_twohalf-D_full','mixed_defect':'I_twohalf-I_full','continuous_target':'true F0+lambda H+S B flow; separate from all discrete quantities'},'synthetic':synth,'synthetic_mixed_defect':synth['twohalf']['mixed_interval']-synth['full']['mixed_interval'],'actual_owner_D':None,'actual_owner_I':None,'actual_owner_HH_defect':None,'actual_owner_mixed_defect':None,'physical_sign_certified':False,'actual_delta3_scale_checked':False,'Taylor_numbers_acceptance_reference':False})
source_binding=E/'repo/research/r31ao_unequal_ladder/ncp_energy06e_certificate_20261010_v1/FINAL_SOURCE_BINDING_V4.json';cp=json.loads(Path('/root/WU088_HH_ENERGY06C_20261009/run/CHECKPOINT_STATUS.json').read_text())
put('MODEL_AND_CORNER_IDENTITY.json',{'status':'EXACT_IDENTITY_CONTRACT_IMPLEMENTED__NATIVE_CORNERS_NOT_DISPATCHED','HH_PHYS01_archive':{'bytes':(W/'HH_PHYS01.zip').stat().st_size,'sha256':sha(W/'HH_PHYS01.zip')},'manifest_payloads':66,'dependency_checks':'5 recovered source .rs hashes match original owner dependency in FINAL_SOURCE_BINDING_V4; SELECTED_SOURCE checked separately','physical_analysis_basis':{'path':str(D/'inputs/SELECTED_SOURCE.json'),'sha256':sha(D/'inputs/SELECTED_SOURCE.json'),'not_new_native_initial_state':True},'actual_owner_source_binding':{'path':str(source_binding),'sha256':sha(source_binding)},'future_corner_proposal':{'common_initial_checkpoint':cp['members']['member1.bin'],'theta':'same FLRW native configuration for all corners','lambda_S':[['1','5e-15'],['1','0'],['0','5e-15'],['0','0']],'t0':1.6e11,'dt':1.25e9,'S_zero':'future birth only0; prior stock/gas/guards/compensations unchanged','native_parameter_source_family_implemented':False,'actual_corner_receipts':None,'not_equivalent_to_old_member_ON_OFF_history':True},'synthetic_model':{'kind':'EXPLICITLY_SYNTHETIC_ISOTHERMAL_TWO_COORDINATE','q':'k*(1-x)^2','no_full_HHe_thermal':True,'A':'1','k':'1/10','initial_x':'1/4','initial_photons':'1/10','theta':'fixed synthetic geometry','lambda_rectangle':['0','1'],'source_rectangle':['0','1/5'],'h':'1/16','fixed_root_domain':['0','1'],'fixed_C':'inverse full chain M at predeclared x=1/2, parameter and incoming photon interval midpoints; per stage fixed','bisection_cuts':80,'not_chosen_from_HH_PHYS01_scale':True},'native_grid':'unchanged128x33','birth_measure':'owner original time/geometry weights; no forced normalization/equality'})
put('ROOT_PRECONDITIONER_BINDING.json',{'native_status':'OPEN','trusted_native_root':None,'trusted_native_parameter_tube':None,'native_preconditioner':None,'ENERGY06E_audit_sha256':sha(E/'run/CERTIFICATE_PRECONDITIONER_AUDIT.json'),'source_binding_sha256':sha(source_binding),'native_chain':'M=I-dt F_y, F_y includes reduced P=N/(1+dt opacity(y)) chain; fixed C must be trusted producer bound to input/source/ABI/root','mixed_implicit_equation':'M v_lambdaS = -R_lambdaS - R_ylambda v_S - R_yS v_lambda - R_yy[v_lambda,v_S], with all previous gas/photon/birth sensitivities included in R parameter jets','synthetic_certificates':{k:v['certificates']for k,v in synth.items()},'synthetic_source_sha256':sha(P/'src/mixed_family.py'),'synthetic_never_native_proof':True,'free_C_or_error_bar_admitted':False})
put('REMAINDER_OR_UNRESOLVED.json',{'status':'UNRESOLVED_ACTUAL_OWNER_AND_TRUE_FLOW','actual_native_interval_I':None,'finite_macro_mixed_remainder':None,'continuous_time_source_law_error':None,'imported_leading_coefficient':'-lambda S A q(4+Xi)delta^3/6','Xi_sign_at_stored_point':'positive; inherited PHYS01 local analysis only','BE_full_factor':'-(3+Xi), frozen constant-source leading coefficient only','BE_twohalf_factor':'-(13/8+Xi/2), same limitation','endpoint_birth_then_BE':'not physical terminal delta-kick','missing':['trusted native mixed/four-corner correlated tube with full H/He thermal and photon chain','source-family ABI, original guards/compensation, fixed native C and exact input provenance','actual density/energy/angle/threshold/hat-cell derivative and remainder support','exact new execution approval and finite live resource/loader/budget binding'],'no_sign_or_scale_fitting':True,'no_Bianchi_global_first_order_cancellation_or_epsilon2_claim':True,'peer_owners_separate':['REI PHYS19/PHYS20 HH-OFF continuous/Bianchi','HE E13C1 photon-only chronology']})
put('EXECUTION_AUTHORIZATION_RECEIPT.json',{'current_exact_native_budget':{'native_dispatch':0,'native_BE_root_calls':0,'macros':0,'legacy_atomic_integrations':0,'retry':0},'authorization_record':None,'parent_scope_proposal_sha256':sha(Path('/root/WU088_HH_ENERGY06C_20261009/run/OWNER_PAIRED_NEW_SCOPE_PROPOSAL_V2.json')),'consumed_old_scopes':['FD1','FD2','6cell'],'future_minimum_proposal_only':{'macros':1,'fixed_theta_baselines':1,'corners':4,'max_full_half_half_endpoint_calls':12,'concurrency':1,'retry':0,'wall_budget':None,'memory_budget':None,'request_ready':False,'not_authorization':True,'no_automatic_corner_replay':True},'executed_non_scientific_budget':{'new_test_methods':10,'whole_PHYS01_suite_replays':0,'symbolic_point_and_causal_replays':0,'synthetic_point_bracket_cuts_per_stage':80,'synthetic_family_domain':'x in[0,1],h<=1/16 exact rational','no_runtime_configuration_change':True}})
put('FAILURE_CLASSIFICATION.json',{'physics':'no actual finite-delta prediction certified','mathematics':'native mixed tube/true flow remainder unresolved','numerics':'native C/chain/guards/source-family identity unresolved; synthetic exact proof separate','implementation':{'first_new_tests':'PASS10; no assertion RED claimed','first_warning':'SyntaxWarning invalid decimal literal at 3for; inserted whitespace only, original log retained','final_warning_as_error_tests':'PASS10'},'environment':'new Python algebra only; no new native live execution','authorization':'absent; native dispatch0','old_PHYS01_failure_logs':'preserved original archive payloads, not rerun'})
# Protect G256 actual final checkpoint files explicitly, in addition to inherited inventory.
old_inv=json.loads((R/'PRESERVATION_BEFORE.json').read_text());g=Path('/root/WU088_HH_MASTER_EXEC_20261008/inputs/on06g/HH_ON06G_20261008_v1/results/segment02b/generation_000032');gfiles=[]
for p in sorted(g.iterdir()):
 if p.is_file():gfiles.append({'path':str(p),'bytes':p.stat().st_size,'sha256':sha(p)})
put('G256_CHECKPOINT_PRESERVATION.json',{'files':gfiles,'accepted_total':256,'time_s':3.2e11,'replay':False})
assert all(sha(Path(x['path']))==x['sha256']for x in old_inv['files']);put('PRESERVATION_AFTER.json',{'inherited_files_checked':len(old_inv['files']),'mismatches':0,'G256_files':gfiles,'old_checkpoint_state_modified':False,'old_worktree_clean':subprocess.check_output(['git','status','--short'],cwd='/root/WU088_HH',text=True)==''})
put('CLAIM_LEDGER.json',{'status':'BOUNDED_MIXED_CONTRACT_IMPLEMENTATION_RETURN','physics':'imported local asymptotic HH suppression only; no total HH_ON-OFF negative claim','mathematics':'synthetic implicit mixed-family enclosures verified; native/continuous remainder OPEN','numerics':'exact rational synthetic; no precision/tolerance/radius downgrade','implementation':'fourcorner identity and carried gas/photon sensitivity contracts verified','environment':'no new native science process','authorization':None,'source_dispatch':0,'legacy_integrations':0,'C1':{'bounded':24,'total':289,'unbounded':265,'epsilon_C':None,'epsilon_R':None,'B22':'OPEN'},'canonical_S0':'OFF control unchanged','ON06G':{'macros':256,'t':3.2e11,'rerun':False},'physical':'HOLD','production':'HOLD','native_candidate_promotion':False})
put('FINAL_VERIFICATION.json',{'import_manifest':{'argv':cmd,'exit':r.returncode,'payloads':66},'new_contract_tests':{'argv':cmd2,'exit':r2.returncode,'unique_tests':10,'old_suite_rerun':False},'same_dependencies_checked':True,'new_native_science_dispatch':0,'native_root_certified':False,'true_flow_remainder_certified':False,'synthetic_interval_family_only':True,'original_files_checked':len(old_inv['files']),'CPU':next(l.split(':',1)[1].strip()for l in Path('/proc/cpuinfo').read_text().splitlines()if l.startswith('model name')),'Python':sys.version,'precision':'exact Fraction synthetic algebra; original native binary64 and128 contracts unchanged'})
(R/'RUN_LEDGER.jsonl').write_text(json.dumps({'event':'PHYS01_IMPORT_MANIFEST_AND_DEPENDENCY_BINDING','payloads':66,'suite_replay':False,'native_dispatch':0})+'\n'+json.dumps({'event':'NEW_SYNTHETIC_MIXED_FAMILY_AND_FOURCORNER_TESTS','tests':10,'actual_owner_I':None,'authorization':None,'root_tolerance_change':False})+'\n')
report='''# HH-PHYS01 NCP 적용 한정 반환

**FOUR_CORNER_CONTRACT_AND_SYNTHETIC_DISCRETE_MIXED_FAMILY_VERIFIED__ACTUAL_OWNER_AND_REMAINDER_OPEN**.
새 native science/BE root/macro/legacy atomic dispatch 각각0. 현재 정확 실행 예산은0이며 authorization=null이다.

HH-PHYS01 ZIP SHA 977ac57dc2aadfb15235c6c8e18edd495927ee8f7a68a62592273c7862b4c96c (71498bytes), manifest66 PASS. INPUT_IDENTITY/THEORY/LOCAL_COEFFICIENTS_FINAL/SYMBOLIC/CAUSAL_KERNEL과 정확 source dependency를 읽었다. 원 PHYS01 전체suite·symbolic·localpoint·causal kernels를 재실행하지 않았다. 5 recovered Rust source hashes가 FINAL_SOURCE_BINDING_V4의 원 source와 같다.

D(전체HH응답), I(새S와finite mixed), full/twohalfHH defect, mixeddefect, true source-law/time error를 별도 object로 구분했다. 네 코너의 초기state/θ/source-law/birthmeasure/clock/h/scheme SHA 일치 계약을 구현했다. S0은 미래방출만0이고 기존photon/gas/guards/compensation을 지우지 않는다. 제안nativebaseline은 원 member1 seed를 모든 corner가 공유하는 새 family이며 기존ON/OFF history 반환을 모서리로 재사용하지 않는다. native corner receipts는 없다.

새 exact-rational 합성 isothermal two-coordinate BE family q=k(1-x)^2에서 full 및 linkedtwohalf의 ∂λ∂S를 interval Jet으로 운반한다. 원BE와 같은 P=(Pprev+hS)/(1+hA(1-x)) elimination 구조의 full chainM를 써서 source-fixedC, Krawczyk strictimage inclusion 및 contraction<1을 검증한다. previousgas/photon first/secondsensitivities와 birth를 residual에 보존하고 implicitmixed derivatives를 계산한다. I=L*S*integral(x_lambdaS) enclosure를 반환하고 독립 monotone80cut rational fourcorner brackets가 그안에 있음을 검사했다. 공유 polynomial coefficient 오차는 correlated difference에서 정확 소거한다. 이것은 명시적 합성모델이며 FT03+H/He/thermal/Xi나 native root 인증이 아니다. 합성certificates에는 native_trusted=false를 고정했다.

실제 ENERGY06E trusted source-bound root/parameter tube/exporter, C provenance 및 정확새승인 부재는 그대로다. Native API는 missing approval/forgedJSON certificate를 거절하고 실제 D/I/defect/remainder는null/OPEN이다. 그실제 source-family 구현과 trustedtube 연결은 다음 작업이며 이번synthetic proof로 대체하지 않는다. h의Taylor숫자로 root폭/tolerance/sign을 맞추지 않았다. 물리 leadingI의 음수는 충분히작은delta의비가산억제이지 전체 HH_ON-OFF부호가 아니다. frozenBE -(3+Xi),-(13/8+Xi/2)는 actualmacro acceptance reference가 아니다. continuous목표는 trueF0+λH+SB이며 endpointbirth뒤fullBE를 terminalphysicalkick로 취급하지 않는다. normalizedmonochromatic weights lowestorder 결과를 Bianchiglobalε²/thresholdsmoothness로 확대하지 않는다.

새시험10 PASS. 최초실행도PASS였고 assertionRED를 주장하지 않는다. Python SyntaxWarning '3for'를 확인하고 whitespace만 고쳐 -Werror final10PASS; 최초 원로그보존. physics/mathematics/numerics/implementation/environment/authorization 실패와OPEN을 FAILURE_CLASSIFICATION에 분리했다. 계승 보호파일 전체bytehash와 원 G256최종checkpoint를 검증했고 이전mutable worktree/registry/DB는 수정하지 않았다. 재실행/자동retry/전역설정변경 없음.

향후 제안은 같은θ/초기state에서최대1macro/4corners/12full-half-halfendpointcalls(기존총endpoint상한이내 제안),concurrency1,retry0이다. Wall/memory/liveownerbinding은null/OPEN이고 request_ready=false이며 승인이아니다. Coupled tube가닫힌뒤 정확scope 승인을별도로 받아야 실제 intervalmixed차이/remainder를 계산할수있다.

C1 24/289·265unbounded,epsilon_C/R=null,B22OPEN,canonicalS0OFFcontrol,ON06G256/t3.2e11s,physical/productionHOLD 유지. REI PHYS19/PHYS20,HE E13C1은 별도owner 결과이며 HH로이식하지않는다. 원자적분재개 없음. Git/양cloud create-onlyACK와 actualrestore는 detachedDELIVERY_RECEIPT를따르며 서로분리한다.
'''
(R/'RETURN_KO.md').write_text(report);(R/'NEXT_HANDOFF_KO.md').write_text('''# 다음 인계
실제 full FT03+H/He source의 λ/S family adapter와 birth/gas/photon mixed sensitivities, fullchain Jacobian/fixedC/sourceABI/hash trusted exporter 및 roottube를 닫는다. 새 정확humanapproval와finite livebudget/binding 전 native science0. 최대1macro제안은 승인아님; wall/memory미정. 실제interval I 또는remainder를 delta3진단숫자에맞추지 않는다. S0과기존stock분리, 동일stateθ, exacthalf1→half2 보존. Trueflow source-law error와 D/I/HHdefect/mixeddefect 구분. 원 consumedscopes/G256/C1coverage/physicalproductionHOLD 유지.
''')
shutil.copytree(R,P/'evidence');
for n in ['RETURN_KO.md','NEXT_HANDOFF_KO.md']:shutil.copyfile(R/n,P/n)
for p in [W/'prepare.py',Path(__file__)]:shutil.copyfile(p,P/p.name)
(P/'REPRODUCE_KO.md').write_text('PYTHONDONTWRITEBYTECODE=1 python3 -W error -m unittest discover -s tests -v\n새10개합성/계약시험만수행. PHYS01전체suite/actualnative/root/history를실행하지않는다. Native API는 approval과trustedtube부재를거절한다.\n')
files={str(p.relative_to(P)):{'bytes':p.stat().st_size,'sha256':sha(p)}for p in sorted(P.rglob('*'))if p.is_file()and '__pycache__'not in p.parts and p!=P/'FILE_MANIFEST.json'};(P/'FILE_MANIFEST.json').write_text(json.dumps({'files':files,'native_science_dispatch':0},indent=2)+'\n')
print('FINAL_PASS','new_tests10','manifest66','protected',len(old_inv['files']),'G256',len(gfiles),'payloads',len(files))
