use rei_microphysics::paired_runtime::*;
use rei_microphysics::coupled_primary::HhMode;
fn config(mode:HhMode)->HhRunConfig{HhRunConfig::new(PairedConfig{spectral_subdivisions:8,n_mu:4,n_phi:8},[1e-14;3],mode).unwrap()}
#[test] fn on_transaction_has_hh_event_after_transport_and_emission(){let c=config(HhMode::Lcs91);let s=hh_paired_initial(&c).unwrap();let t=hh_paired_trial(&c,&s,1.25e9).unwrap();assert!(t.state.hh_events_per_h()>0.0,"LCS selector must invoke HH source at the actual paired transaction");assert!(t.state.hh_heat_ev_per_h()<0.0);}
#[test] fn off_transaction_is_exact_original_delegation(){let c=config(HhMode::Off);let s=hh_paired_initial(&c).unwrap();let a=paired_trial(c.grid(),c.hubble(),s.base(),1.25e9).unwrap();let b=hh_paired_trial(&c,&s,1.25e9).unwrap();assert_eq!(format!("{:?}",a.state),format!("{:?}",b.state.base()));assert_eq!(a.audits,b.audits);assert_eq!(a.local_bound.to_bits(),b.local_bound.to_bits());assert_eq!(b.state.hh_events_per_h(),0.0);}
#[test] fn mismatched_mode_cannot_reuse_state(){let c=config(HhMode::Off);let s=hh_paired_initial(&c).unwrap();let bad=config(HhMode::Lcs91);assert!(hh_paired_trial(&bad,&s,1.25e9).is_err(),"state must bind original selection");}
#[test] fn only_accepted_halves_enter_hh_ledger(){let c=config(HhMode::Lcs91);let s=hh_paired_initial(&c).unwrap();let t=hh_paired_trial(&c,&s,1.25e9).unwrap();let j=t.source_hh_events;assert!(j.iter().all(|x|*x>0.0));assert_eq!(t.state.hh_events_per_h().to_bits(),(j[1]+j[2]).to_bits());assert_ne!(t.state.hh_events_per_h().to_bits(),(j[0]+j[1]+j[2]).to_bits());for (a,j) in t.source_hh_heat.iter().zip(j){assert_eq!(a.to_bits(),(-13.598434599702*j).to_bits());}}
#[test] fn whole_ensemble_rolls_back_after_later_failure(){let c=config(HhMode::Lcs91);let bad=config(HhMode::Off);let s=hh_paired_initial(&c).unwrap();let mut states=vec![s.clone(),s];let before=format!("{:?}",states);let e=try_hh_paired_ensemble(&[c,bad],&mut states,1.25e9).unwrap_err();assert_eq!(e.code(),"HH_PAIRED_IDENTITY");assert_eq!(format!("{:?}",states),before);}
#[test] fn invalid_dt_does_not_commit_state_or_counters(){let c=config(HhMode::Lcs91);let mut s=hh_paired_initial(&c).unwrap();let before=format!("{:?}",s);assert_eq!(try_hh_paired_step(&c,&mut s,f64::NAN).unwrap_err().code(),"PAIRED_TRIAL_DOMAIN");assert_eq!(format!("{:?}",s),before);}
#[test] fn root_and_point_carry_into_next_transaction(){let c=config(HhMode::Lcs91);let s=hh_paired_initial(&c).unwrap();let t=hh_paired_trial(&c,&s,1.25e9).unwrap();let u=hh_paired_trial(&c,&t.state,1.25e9).unwrap();assert_eq!(u.state.base().time_s,2.5e9);assert!(u.state.hh_events_per_h()>t.state.hh_events_per_h());assert!(u.audits.iter().all(|a|a.contains("\"carry_gas\"")&&a.contains("\"root_image\"")&&a.contains("\"hh_mode\":\"LCS\"")));}
#[test] fn checkpoint_roundtrip_preserves_accepted_state_and_continuation(){let c=config(HhMode::Lcs91);let s=hh_paired_initial(&c).unwrap();let a=hh_paired_trial(&c,&s,1.25e9).unwrap().state;let bytes=hh_checkpoint_encode(&c,&a).unwrap();assert!(!bytes.is_empty(),"checkpoint must contain accepted state and all compensated ledgers");let b=hh_checkpoint_decode(&c,&bytes).unwrap();assert_eq!(format!("{:?}",a),format!("{:?}",b));let ta=hh_paired_trial(&c,&a,1.25e9).unwrap();let tb=hh_paired_trial(&c,&b,1.25e9).unwrap();assert_eq!(ta.audits,tb.audits);assert_eq!(format!("{:?}",ta.state),format!("{:?}",tb.state));}
#[test] fn checkpoint_rejects_cross_provider(){let off=config(HhMode::Off);let on=config(HhMode::Lcs91);let bytes=hh_checkpoint_encode(&off,&hh_paired_initial(&off).unwrap()).unwrap();assert!(hh_checkpoint_decode(&on,&bytes).is_err(),"checkpoint cannot be relabelled as another provider");}
#[test] fn checkpoint_rejects_truncation(){let c=config(HhMode::Lcs91);assert!(hh_checkpoint_decode(&c,&[1,2,3]).is_err());}
#[test] fn checkpoint_detects_bit_corruption(){let c=config(HhMode::Lcs91);let s=hh_paired_initial(&c).unwrap();let mut b=hh_checkpoint_encode(&c,&s).unwrap();let i=b.len()/2;b[i]^=1;assert_eq!(hh_checkpoint_decode(&c,&b).unwrap_err().code(),"HH_CHECKPOINT_CHECKSUM");}
#[test] fn checkpoint_rejects_other_geometry(){let c=config(HhMode::Lcs91);let s=hh_paired_initial(&c).unwrap();let b=hh_checkpoint_encode(&c,&s).unwrap();let other=HhRunConfig::new(c.grid().clone(),[1.01e-14,0.99e-14,1e-14],HhMode::Lcs91).unwrap();assert_eq!(hh_checkpoint_decode(&other,&b).unwrap_err().code(),"HH_CHECKPOINT_IDENTITY");}
#[test] fn checkpoint_rejects_other_grid(){let c=config(HhMode::Lcs91);let s=hh_paired_initial(&c).unwrap();let b=hh_checkpoint_encode(&c,&s).unwrap();let other=HhRunConfig::new(PairedConfig{spectral_subdivisions:16,n_mu:4,n_phi:8},c.hubble(),HhMode::Lcs91).unwrap();assert_eq!(hh_checkpoint_decode(&other,&b).unwrap_err().code(),"HH_CHECKPOINT_IDENTITY");}
#[test] fn checkpoint_portable_header_and_exact_reencoding(){let c=config(HhMode::Off);let s=hh_paired_initial(&c).unwrap();let b=hh_checkpoint_encode(&c,&s).unwrap();assert_eq!(&b[..8],b"HH06Bv01");let t=hh_checkpoint_decode(&c,&b).unwrap();assert_eq!(hh_checkpoint_encode(&c,&t).unwrap(),b);}
#[test] fn bad_configuration_is_rejected(){assert!(HhRunConfig::new(PairedConfig{spectral_subdivisions:0,n_mu:4,n_phi:8},[1e-14;3],HhMode::Lcs91).is_err());assert!(HhRunConfig::new(PairedConfig{spectral_subdivisions:8,n_mu:4,n_phi:8},[f64::NAN,1e-14,1e-14],HhMode::Lcs91).is_err());}
#[test] fn failed_local_gate_rolls_back_every_field(){let c=config(HhMode::Lcs91);let mut s=hh_paired_initial(&c).unwrap();let b=hh_checkpoint_encode(&c,&s).unwrap();let e=try_hh_paired_step(&c,&mut s,1e11).unwrap_err();assert_eq!(e.code(),"PAIRED_LOCAL_GATE");assert_eq!(hh_checkpoint_encode(&c,&s).unwrap(),b);}
#[test] fn bianchi_off_delegates_original_audits(){let c=HhRunConfig::new(PairedConfig{spectral_subdivisions:8,n_mu:4,n_phi:8},[1.01e-14,0.99e-14,1e-14],HhMode::Off).unwrap();let s=hh_paired_initial(&c).unwrap();let a=paired_trial(c.grid(),c.hubble(),s.base(),1.25e9).unwrap();let b=hh_paired_trial(&c,&s,1.25e9).unwrap();assert_eq!(a.audits,b.audits);assert_eq!(format!("{:?}",a.state),format!("{:?}",b.state.base()));}
#[test] fn new_on_certificate_is_in_actual_audit(){let c=config(HhMode::Lcs91);let s=hh_paired_initial(&c).unwrap();let t=hh_paired_trial(&c,&s,1.25e9).unwrap();for a in &t.audits{assert!(a.contains("\"centre_rhs\"")&&a.contains("\"box_jacobian\"")&&a.contains("\"root_image\""));}assert!(t.local_bound<2e-4&&t.public_width<2e-3&&t.max_ledger<=1e-12);}
