use rei_microphysics::{Interval, StepControl};
use rei_microphysics::coupled_primary::*;
fn fixture()->(PrimaryStage,PrimaryState,StepControl){
 let stage=PrimaryStage{n_h_cm3:1e-4,f_he:0.083,h_mean_per_s:1e-14};
 let w=1.5*(1.380649e-16/1.602176634e-12)*50000.0*(1.0+stage.f_he+0.9+stage.f_he*(0.3+2.0*0.6));
 let s=PrimaryState{fractions:[0.9,0.3,0.6],w_ev_per_h:w,escape_ev_per_h:0.0,packets:vec![PrimaryPacket{energy_ev:13.7,per_h:0.05}]};
 (stage,s,StepControl{max_iterations:80,residual_tolerance:1e-14})
}
fn parent(s:&PrimaryState)->PrimaryBox{PrimaryBox{gas:[s.fractions[0],s.fractions[1],s.fractions[2],s.w_ev_per_h].map(|x|Interval::point(x).unwrap()),photons:s.packets.iter().map(|p|Interval::point(p.per_h).unwrap()).collect()}}
#[test] fn on_has_real_hh_event_and_binding_heat(){let(g,s,c)=fixture(); let r=hh_stage_step(&g,&s,1e9,c,HhMode::Lcs91).expect("active HH stage"); assert!(r.hh_events_per_h>0.0);assert_eq!(r.hh_heat_ev_per_h,-13.598434599702*r.hh_events_per_h);assert_eq!(r.mode,HhMode::Lcs91);}
#[test] fn off_delegates_all_original_point_fields(){let(g,s,c)=fixture();let a=primary_stage_step(&g,&s,1e9,c).unwrap();let b=hh_stage_step(&g,&s,1e9,c,HhMode::Off).unwrap();assert_eq!(format!("{:?}",a),format!("{:?}",b.base));assert_eq!(b.hh_events_per_h,0.0);}
#[test] fn new_on_root_strictly_maps_into_new_box(){let(g,s,c)=fixture();let r=hh_stage_root(&g,&s,&parent(&s),1e9,c,HhMode::Lcs91).expect("new ON root");assert!(r.root.q<1.0);for i in 0..4{assert!(r.root.gas[i].lo<r.image[i].lo&&r.image[i].hi<r.root.gas[i].hi);}assert_eq!(r.mode,HhMode::Lcs91);}
#[test] fn jet_contains_value_and_has_nonzero_curvature(){let(g,s,_)=fixture();let j=hh_rate_jet(&g,&parent(&s).gas).unwrap();assert!(j.value.lo>0.0);assert!(j.gradient[0].hi<0.0);assert!(j.hessian[0][0].lo>0.0);}
#[test] fn whole_box_temperature_guard_is_required(){let(g,s,_)=fixture();let mut bx=parent(&s).gas;bx[3]=Interval::new(0.1,s.w_ev_per_h).unwrap();assert_eq!(hh_rate_jet(&g,&bx).unwrap_err().code(),"HH_ON06_TEMPERATURE_DOMAIN");}
#[test] fn root_rejects_wrong_parent_identity_point(){let(g,s,c)=fixture();let mut bx=parent(&s);bx.gas[0]=Interval::point(0.1).unwrap();assert_eq!(hh_stage_root(&g,&s,&bx,1e9,c,HhMode::Lcs91).unwrap_err().code(),"PRIMARY_PARENT_GAS");}
#[test] fn absent_neutral_source_jet_is_finite_at_h_one(){let(g,s,_)=fixture();let mut bx=parent(&s).gas;bx[0]=Interval::point(1.0).unwrap();let j=hh_rate_jet(&g,&bx).unwrap();assert!(j.value.lo<=0.0&&j.value.hi>=0.0);assert!(j.gradient[0].lo<=0.0&&j.gradient[0].hi>=0.0);assert!(j.hessian[0][0].lo>0.0);}
#[test] fn neutral_initial_state_can_seed_without_electrons(){let(g,mut s,c)=fixture();s.fractions=[0.0,0.0,0.0];s.packets.clear();s.w_ev_per_h=1.5*(1.380649e-16/1.602176634e-12)*50000.0*(1.0+g.f_he);let r=hh_stage_step(&g,&s,1e8,c,HhMode::Lcs91).unwrap();assert!(r.base.state.fractions[0]>0.0&&r.hh_events_per_h>0.0);}
#[test] fn off_conservative_is_exact_delegation(){let(g,s,c)=fixture();let(a,ac)=primary_stage_step_conservative(&g,&s,1e9,c,1e-18).unwrap();let(b,bc)=hh_stage_step_conservative(&g,&s,1e9,c,1e-18,HhMode::Off).unwrap();assert_eq!(format!("{:?}",a),format!("{:?}",b.base));assert_eq!(ac.to_bits(),bc.to_bits());}
#[test] fn conservative_on_point_is_in_fresh_root_box(){let(g,s,c)=fixture();let(p,_)=hh_stage_step_conservative(&g,&s,1e10,c,0.0,HhMode::Lcs91).unwrap();let r=hh_stage_root(&g,&s,&parent(&s),1e10,c,HhMode::Lcs91).unwrap();let y=[p.base.state.fractions[0],p.base.state.fractions[1],p.base.state.fractions[2],p.base.state.w_ev_per_h];for i in 0..4{assert!(r.root.gas[i].lo<=y[i]&&y[i]<=r.root.gas[i].hi);}}
#[test] fn root_mode_replay_is_rejected(){let(g,s,c)=fixture();let p=parent(&s);let r=hh_stage_root(&g,&s,&p,1e9,c,HhMode::Lcs91).unwrap();assert!(hh_root_matches(&r,&g,&s,&p,1e9,c,HhMode::Lcs91));assert!(!hh_root_matches(&r,&g,&s,&p,1e9,c,HhMode::Off));}
#[test] fn root_dt_and_parent_replay_are_rejected(){let(g,s,c)=fixture();let mut p=parent(&s);let r=hh_stage_root(&g,&s,&p,1e9,c,HhMode::Lcs91).unwrap();assert!(!hh_root_matches(&r,&g,&s,&p,2e9,c,HhMode::Lcs91));p.photons[0].hi+=1e-15;assert!(!hh_root_matches(&r,&g,&s,&p,1e9,c,HhMode::Lcs91));}
#[test] fn root_carries_nonzero_incoming_box(){let(g,s,c)=fixture();let mut p=parent(&s);for x in &mut p.gas{x.lo-=1e-12;x.hi+=1e-12;}p.photons[0].lo-=1e-14;p.photons[0].hi+=1e-14;let r=hh_stage_root(&g,&s,&p,1e9,c,HhMode::Lcs91).unwrap();assert!(r.root.q<1.0);assert!(r.root.gas[0].hi-r.root.gas[0].lo>1e-12);}
#[test] fn failed_try_does_not_mutate_caller(){let(g,mut s,c)=fixture();let before=format!("{:?}",s);assert!(try_hh_stage_step(&g,&mut s,f64::NAN,c,HhMode::Lcs91).is_err());assert_eq!(before,format!("{:?}",s));}
#[test] fn zero_step_has_no_events(){let(g,s,c)=fixture();let r=hh_stage_step(&g,&s,0.0,c,HhMode::Lcs91).unwrap();assert_eq!(r.hh_events_per_h,0.0);assert_eq!(format!("{:?}",r.base.state),format!("{:?}",s));}
#[test] fn on_rejects_outside_rate_domain_even_at_zero_dt(){let(g,mut s,c)=fixture();s.w_ev_per_h*=1.5;assert_eq!(hh_stage_step(&g,&s,0.0,c,HhMode::Lcs91).unwrap_err().code(),"HH_ON06_TEMPERATURE_DOMAIN");}
#[test] fn on_interval_difference_contains_hh_jets_and_preserves_he(){let(g,s,_)=fixture();let p=parent(&s);let(a,_)=hh_interval_source(&g,&s,&p.gas,&p.photons,1e9,HhMode::Off).unwrap();let(b,_)=hh_interval_source(&g,&s,&p.gas,&p.photons,1e9,HhMode::Lcs91).unwrap();let q=hh_rate_jet(&g,&p.gas).unwrap();let delta=b[0].value.sub(&a[0].value).unwrap();assert!(delta.lo<=q.value.lo&&q.value.hi<=delta.hi);for i in [1,2]{assert_eq!(a[i].value.lo.to_bits(),b[i].value.lo.to_bits());assert_eq!(a[i].value.hi.to_bits(),b[i].value.hi.to_bits());}}
#[test] fn no_direct_photon_derivatives_in_hh_jet(){let(g,s,_)=fixture();let j=hh_rate_jet(&g,&parent(&s).gas).unwrap();for k in 4..7{assert!(j.gradient[k].lo<=0.0&&j.gradient[k].hi>=0.0);}}
#[test] fn carry_keeps_numerical_photon_and_exact_discrete_root(){let(g,s,c)=fixture();let p=parent(&s);let(step,_)=hh_stage_step_conservative(&g,&s,5e9,c,0.0,HhMode::Off).unwrap();let root=hh_stage_root(&g,&s,&p,5e9,c,HhMode::Off).unwrap();let out=hh_return_enclosure(&g,&s,&p,5e9,c,&step,&root).unwrap();for (x,b) in step.base.state.packets.iter().zip(&out.photons){assert!(b.lo<=x.per_h&&x.per_h<=b.hi);}for (a,b) in root.root.photons.iter().zip(&out.photons){assert!(b.lo<=a.lo&&a.hi<=b.hi);}}
#[test] fn stale_hh_counter_cannot_enter_return_enclosure(){let(g,s,c)=fixture();let p=parent(&s);let(mut step,_)=hh_stage_step_conservative(&g,&s,1e9,c,0.0,HhMode::Lcs91).unwrap();let root=hh_stage_root(&g,&s,&p,1e9,c,HhMode::Lcs91).unwrap();step.hh_events_per_h=0.0;assert_eq!(hh_return_enclosure(&g,&s,&p,1e9,c,&step,&root).unwrap_err().code(),"HH_ON06_RETURN_EVENT");}
