"""Validate order/source metadata before accessing any direct matrix payload."""
from decimal import Decimal
import hashlib
import json
from pathlib import Path
import re


def digest(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def _unique(pairs):
    out={}
    for key,value in pairs:
        if key in out:
            raise ValueError('duplicate metadata key: '+key)
        out[key]=value
    return out


def parse(raw):
    def reject(value):
        raise ValueError('nonfinite JSON metadata: '+value)
    obj=json.loads(raw,parse_int=Decimal,parse_float=Decimal,
                   parse_constant=reject,object_pairs_hook=_unique)
    if not isinstance(obj,dict):
        raise ValueError('metadata object required')
    return obj


def check_identities(od_raw,jvp_raw,order,contract):
    if type(order) is not int or order not in (128,160,192):
        raise ValueError('locked ladder order required')
    od,jvp=parse(od_raw),parse(jvp_raw)
    for obj in (od,jvp):
        n=obj.get('n')
        z=obj.get('z')
        if not isinstance(n,Decimal) or n!=order:
            raise ValueError('order identity drift')
        if isinstance(z,bool) or not isinstance(z,(str,Decimal)):
            raise ValueError('geometry identity type')
        z=Decimal(z)
        if not z.is_finite() or z!=Decimal('0.75'):
            raise ValueError('geometry identity drift')
    expected=contract['orders'][str(order)]
    for key,want in expected['OD_identity'].items():
        if od.get(key)!=want:
            raise ValueError('OD source/grid identity drift: '+key)
    for key,want in expected['JVP_identity'].items():
        if jvp.get(key)!=want:
            raise ValueError('JVP source/grid identity drift: '+key)
    # The full three-plane OD tensor is generated by the unchanged, pinned
    # grid/contract source; the JVP file pins its first (U,U) plane exactly.
    if not isinstance(od.get('W_sha256'),str) or not re.fullmatch('[0-9a-f]{64}',od['W_sha256']):
        raise ValueError('OD weight identity missing')
    return True


def check_files(od,jvp,order,contract):
    od,jvp=Path(od),Path(jvp)
    check_identities(od.with_name('IDENTITY.json').read_bytes(),
                     jvp.with_name('IDENTITY.json').read_bytes(),order,contract)
    for path,kind in ((od,'OD'),(jvp,'JVP')):
        result=parse(path.with_name('RESULTS.json').read_bytes())
        if result.get('sha256')!=digest(path):
            raise ValueError(kind+' result byte identity drift')
        if kind=='OD' and (result.get('Hamiltonian_included') is not False or
                           result.get('independent_dotO_included') is not False):
            raise ValueError('OD export scope drift')
        if kind=='JVP' and result.get('status')!='COMPUTED_INDEPENDENT_DERIVATIVE':
            raise ValueError('independent JVP provenance missing')
    return {'OD':digest(od),'JVP':digest(jvp),'order':order,'z_decimal':'0.75'}
